# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "btrfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1ed88b52-379c-4556-8025-c98c996cf005";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/14943ac5-8a70-4052-986b-ed4e8e5fe477";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1ed88b52-379c-4556-8025-c98c996cf005";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1ed88b52-379c-4556-8025-c98c996cf005";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/1ed88b52-379c-4556-8025-c98c996cf005";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/1ed88b52-379c-4556-8025-c98c996cf005";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8389-55EE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/wingej0/Videos" =
    { device = "/dev/disk/by-uuid/7319ff6d-11a8-4909-8bd3-dcc90fdb9036";
      fsType = "btrfs";
      options = [ "subvol=videos" "compress=zstd" ];
    };

  fileSystems."/home/wingej0/Pictures" =
    { device = "/dev/disk/by-uuid/7319ff6d-11a8-4909-8bd3-dcc90fdb9036";
      fsType = "btrfs";
      options = [ "subvol=pictures" "compress=zstd" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bd31d013-0ccf-475b-afec-c4f51303d7c9"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp13s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
